### ISSUE TITLE
Python 2.7.9 certificate problem

### ISSUE THREAD

**Issue by MilhouseVH** [OpenELEC/OpenELEC.tv#3749]
Test:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import urllib2
response = urllib2.urlopen("https://raw.github.com/MilhouseVH/texturecache.py/master/VERSION")
print(response)
```

Result with Python 2.7.9 (latest master, [this build](http://forum.kodi.tv/showthread.php?tid=211501&pid=1879769#pid1879769)):
```
Traceback (most recent call last):
  File "/storage/freenas/data/test.py", line 5, in <module>
    response = urllib2.urlopen("https://raw.github.com/MilhouseVH/texturecache.py/master/VERSION")
  File "/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/Python-2.7.9/.install_pkg/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/Python-2.7.9/.install_pkg/usr/lib/python2.7/urllib2.py", line 431, in open
  File "/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/Python-2.7.9/.install_pkg/usr/lib/python2.7/urllib2.py", line 449, in _open
  File "/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/Python-2.7.9/.install_pkg/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
  File "/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/Python-2.7.9/.install_pkg/usr/lib/python2.7/urllib2.py", line 1240, in https_open
  File "/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/Python-2.7.9/.install_pkg/usr/lib/python2.7/urllib2.py", line 1197, in do_open
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

Result with Python 2.7.3 ([this build](http://forum.kodi.tv/showthread.php?tid=211501&pid=1878490#pid1878490)):
```
<addinfourl at 6708160 whose fp = <socket._fileobject object at 0xb698fdf0>>
```
i.e. no error, `urlopen()` succeeded.

**Comment by stefansaraev** [comment]
fixed in a0c38a4a840decac6000bbd576afd1b4f7d653ba

@sraue for now keep cacert.pem location as-is. for OE 6.0 (but not before) move to /etc/ssl/cert.pem

**Comment by MilhouseVH** [comment]
Thanks, will clean build and confirm.

**Comment by MilhouseVH** [comment]
All good now, many thanks!
