### ISSUE TITLE
UTF8 Locate error

### ISSUE THREAD

**Issue by rafaelrosars** [OpenELEC/OpenELEC.tv#4112]
I have sick rage running with my openelec and i get this error when i hit Settings/Search Settings:

2015-04-27 10:51:44 Thread-35 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 3846, in index
    return t.respond()
  File "/storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotatoHead/sbcache/cheetah/_storage__kodi_addons_service_downloadmanager_SickPotatoHead_resources_SickBeard_gui_slick_interfaces_default_config_search_tmpl.py", line 815, in respond
    if _v is not None: write(_filter(_v, rawExpr=u'$sickbeard.TORRENT_PASSWORD')) # from line 541, col 87.
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 95, in filter
    logger.log(u'Unable to decode using {0}, trying utf-8. Error is: {1}'.format(sickbeard.SYS_ENCODING, ex(e)),logger.DEBUG)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/exceptions.py", line 49, in ex
    e_message = e_message + " : " + fixed_arg
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc5 in position 7: invalid continuation byte

At sick rage forum, solution is to change locale from posix to urf8, but i don't know how to change

**Comment by stefansaraev** [comment]
no support for 3rdparty addons.

**Comment by rafaelrosars** [comment]
I'm just asking how to change locale in openelec, can you help me?

**Comment by stefansaraev** [comment]
hey, this is a bugtracker, not a forum. please ask your questions in the forum.
