### ISSUE TITLE
Wetek Play (OpenELEC Version) freezes

### ISSUE THREAD

**Issue by henkwiedig** [OpenELEC/OpenELEC.tv#4549]
Wektek was in home screen during freeze.
No user interaction was done.

syslog: http://pastebin.com/qi7JGdqu
kodilog: http://pastebin.com/4ffLHviP

Version: OpenELEC (official) Version: 6.0.0 on SD

**Comment by codesnake** [comment]
Unfortunately nothing helpful in your logs. How did you take the logs?

**Comment by s-m-i-c-h-a** [comment]
I have the same problem. Somtimes Kodi freeze.
I capture some logs.

journalctl -f = http://sprunge.us/fjZB
kodi.log = http://sprunge.us/ZXfN

I hope that help to find the problem

**Comment by henkwiedig** [comment]
@codesnake As network also stops working i let tail -f and journalct -f run and waited for the freez. Then pasted the last lines in the shell buffer. Not all obviously.

**Comment by s-m-i-c-h-a** [comment]
@codesnake and henkwiedig : the logiles from my last comment are captured in a "screen" session.
So that content is all until the system are crashed.
As far as I know, you can not get more data's.

journalctl -f = http://sprunge.us/fjZB
kodi.log = http://sprunge.us/ZXfN


I hope that help to find the problem !!!!

**Comment by codesnake** [comment]
@henkwiedig @s-m-i-c-h-a Are both of you using WiFi?

**Comment by henkwiedig** [comment]
No WiFi here !

**Comment by codesnake** [comment]
If I understood correctly the issue is random and cannot be reproduced using some set of steps?

**Comment by s-m-i-c-h-a** [comment]
I also use no WIFI

**Comment by s-m-i-c-h-a** [comment]
Yes, the issue is random and can not reproduced. I have try to reproduce the issue, but with no luck.

**Comment by henkwiedig** [comment]
Here it's the same.
Am 22.01.2016 12:33 schrieb s-m-i-c-h-a <notifications@github.com>:Yes, the issue is random and can not reproduced. I have try to reproduce the issue, but with no luck.

**Comment by s-m-i-c-h-a** [comment]
Since the update 6.0.1, I do not see a freeze up to now.
I will have a look on this and in a case the problem comes back, I will inform you.

**Comment by UC3829** [comment]
When it freezes I can still log in via terminal.  Using the "top" command I see that nothing is hogging the CPU.  Possibly it is related to the PVR, skin or some application.  Samba client is also enabled.  Still freezing here in 6.0.3.  How can we monitor the CPU temperature on this device?

**Comment by UC3829** [comment]
**Process list from "frozen" Kodi system**

```
Mem: 497984K used, 379252K free, 7096K shrd, 50500K buff, 184152K cached
CPU:  0.2% usr  1.5% sys  0.3% nic 97.9% idle  0.0% io  0.0% irq  0.0% sirq
Load average: 0.25 0.72 0.70 1/144 3023

  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 2245  2240 root     S     585m 68.1   0  1.1 /usr/lib/kodi/kodi.bin --standalone -fs --lircdev /run/
 2927     2 root     SW       0  0.0   0  0.2 [kworker/0:1]
 2077     1 root     S     189m 22.0   1  0.1 vdr.bin -g /tmp --no-kbd --log=1 --port=0 --config=/sto
 2996  1901 root     S     6932  0.7   1  0.1 sshd: root@pts/0
 3023  2998 root     R     2680  0.3   1  0.1 top
 1888     2 root     SW       0  0.0   1  0.0 [kworker/1:4]
  857     2 root     SW       0  0.0   0  0.0 [kthread_di]
  103     2 root     SW       0  0.0   0  0.0 [kthread_hdmi]
 1061     2 root     SW       0  0.0   1  0.0 [kthread_hdcp]
 2678  2076 root     S     7884  0.9   1  0.0 /usr/bin/smbd --configfile=/run/samba/smb.conf
 1785     1 root     S     7504  0.8   0  0.0 /usr/lib/systemd/systemd-udevd
 2076     1 root     S     7228  0.8   1  0.0 /usr/bin/smbd --configfile=/run/samba/smb.conf
 2072     1 root     S     7208  0.8   1  0.0 /usr/bin/nmbd --configfile=/run/samba/smb.conf
 2024     1 root     S     5056  0.5   1  0.0 /usr/bin/wpa_supplicant -u
 1901     1 root     S     4372  0.5   1  0.0 /usr/sbin/sshd -D
 1918     1 root     S     4272  0.4   0  0.0 /usr/sbin/connmand -nr --config=/etc/connman/main.conf
    1     0 root     S     4092  0.4   1  0.0 /usr/lib/systemd/systemd
 1798     1 dbus     S     3476  0.4   1  0.0 /usr/bin/dbus-daemon --system --address=systemd: --nofo
 2066     1 root     S     3160  0.3   1  0.0 /usr/bin/rpcbind
 1801     1 root     S     2784  0.3   1  0.0 /usr/sbin/eventlircd -f --evmap=/etc/eventlircd.d --soc
 2998  2996 root     S     2668  0.3   1  0.0 -sh
 1830     1 root     S     2664  0.3   1  0.0 /sbin/crond -f -S
 2240     1 root     S     2664  0.3   1  0.0 {kodi.sh} /bin/sh /usr/lib/kodi/kodi.sh --standalone -f
 1796     1 root     S     2536  0.2   0  0.0 /usr/lib/systemd/systemd-logind
 1422     1 root     S     2452  0.2   1  0.0 /usr/lib/systemd/systemd-journald
 2060     1 root     S     1540  0.1   0  0.0 /usr/bin/brcm_patchram_plus --patchram /lib/firmware/br
 1019     2 root     SW       0  0.0   0  0.0 [kthread_h265]
 1041     2 root     SW       0  0.0   0  0.0 [mmcqd/0]
 1033     2 root     SW       0  0.0   0  0.0 [irq/60-sdio]
    9     2 root     SW       0  0.0   0  0.0 [rcu_sched]
    7     2 root     SW       0  0.0   0  0.0 [migration/0]
 1122     2 root     SW       0  0.0   1  0.0 [jbd2/mmcblk0p2-]
   10     2 root     SW       0  0.0   1  0.0 [migration/1]
  629     2 root     SW       0  0.0   1  0.0 [kworker/1:1]
    3     2 root     SW       0  0.0   0  0.0 [ksoftirqd/0]
 1130     2 root     SW<      0  0.0   1  0.0 [loop0]
  948     2 root     SW       0  0.0   1  0.0 [aml_nftld]
  924     2 root     SW       0  0.0   1  0.0 [aml_nftld]
   11     2 root     SW       0  0.0   1  0.0 [ksoftirqd/1]
  916     2 root     SW       0  0.0   1  0.0 [aml_nftld]
  921     2 root     SW       0  0.0   1  0.0 [aml_nftld]
 2207     2 root     SW       0  0.0   1  0.0 [kdvb-ad-0-fe-0]
  526     2 root     SW       0  0.0   0  0.0 [khubd]
    6     2 root     SW       0  0.0   1  0.0 [kworker/u4:0]
 2846     2 root     SW       0  0.0   1  0.0 [kworker/u4:2]
    4     2 root     SW       0  0.0   0  0.0 [kworker/0:0]
 1036     2 root     SW       0  0.0   1  0.0 [irq/101-mmc_in]
 1037     2 root     SW       0  0.0   1  0.0 [irq/102-mmc_out]
    2     0 root     SW       0  0.0   0  0.0 [kthreadd]
    5     2 root     SW<      0  0.0   0  0.0 [kworker/0:0H]
    8     2 root     SW       0  0.0   0  0.0 [rcu_bh]
   13     2 root     SW<      0  0.0   1  0.0 [kworker/1:0H]
   14     2 root     SW<      0  0.0   0  0.0 [khelper]
   15     2 root     SW       0  0.0   1  0.0 [kdevtmpfs]
   23     2 root     SW<      0  0.0   0  0.0 [suspend]
  508     2 root     SW<      0  0.0   0  0.0 [writeback]
  511     2 root     SW<      0  0.0   0  0.0 [bioset]
  512     2 root     SW<      0  0.0   0  0.0 [crypto]
  514     2 root     SW<      0  0.0   0  0.0 [kblockd]
  630     2 root     SW<      0  0.0   0  0.0 [rpciod]
  638     2 root     SW       0  0.0   1  0.0 [kswapd0]
  683     2 root     SW       0  0.0   1  0.0 [fsnotify_mark]
  700     2 root     SW<      0  0.0   1  0.0 [nfsiod]
  703     2 root     SW<      0  0.0   1  0.0 [cifsiod]
  730     2 root     SW       0  0.0   1  0.0 [khvcd]
  764     2 root     SW<      0  0.0   1  0.0 [iscsi_eh]
  791     2 root     SW       0  0.0   1  0.0 [NULL_task_for_h]
  792     2 root     SW       0  0.0   1  0.0 [cpu_hotplug_gdb]
  793     2 root     RW       0  0.0   1  0.0 [cpu_idle_gdbs]
  835     2 root     SW<      0  0.0   1  0.0 [binder]
  847     2 root     SW       0  0.0   1  0.0 [ge2d_monitor]
  866     2 root     SW<      0  0.0   0  0.0 [dwc_otg]
  869     2 root     SW<      0  0.0   0  0.0 [dwc_otg]
 1051     2 root     SW<      0  0.0   0  0.0 [rtc]
 1063     2 root     SW<      0  0.0   0  0.0 [cec_work]
 1094     2 root     SW<      0  0.0   0  0.0 [deferwq]
 1123     2 root     SW<      0  0.0   0  0.0 [ext4-dio-unwrit]
 1175     2 root     SW<      0  0.0   0  0.0 [kworker/u5:0]
 1198     2 root     SW       0  0.0   1  0.0 [irq/51-ts0_irq]
 1252     2 root     SW<      0  0.0   0  0.0 [cfg80211]
 1764     2 root     SW       0  0.0   0  0.0 [wl_event_handle]
 1765     2 root     SW       0  0.0   0  0.0 [dhd_watchdog_th]
 1766     2 root     SW       0  0.0   0  0.0 [dhd_dpc]
 1767     2 root     SW       0  0.0   0  0.0 [dhd_sysioc]
 2098     2 root     SW<      0  0.0   1  0.0 [hci0]
 2100     2 root     SW<      0  0.0   0  0.0 [hci0]
 2105     2 root     SW<      0  0.0   0  0.0 [kworker/u5:2]
 2440     2 root     SW<      0  0.0   0  0.0 [kworker/0:1H]
 3015     2 root     SW       0  0.0   0  0.0 [kworker/0:2]
```

**Comment by UC3829** [comment]
**Found a method to reproduce this issue:**

Install Vaughn Live from SuperRepo / Video add-ons
Example:

1.  Launch Vaughn Live
2.  Open folder "Top Bar"
3.  Open folder "News & Tech"
4.  Open context menu for gfqnetwork
5.  Choose "Visit Chat" or "Visit Page" [kodi freezes]

**Last log entries:**

```
23:48:33 T:3031430208  NOTICE: Enumerated ALSA devices:
23:48:33 T:3031430208  NOTICE:     Device 1
23:48:33 T:3031430208  NOTICE:         m_deviceName      : default
23:48:33 T:3031430208  NOTICE:         m_displayName     : Default (AML-DUMMY-CODEC S/PDIF)
23:48:33 T:3031430208  NOTICE:         m_displayNameExtra:
23:48:33 T:3031430208  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
23:48:33 T:3031430208  NOTICE:         m_channels        : FL,FR,BL,BR,FC,LFE,SL,SR
23:48:33 T:3031430208  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000
23:48:33 T:3031430208  NOTICE:         m_dataFormats     : AE_FMT_AC3,AE_FMT_DTS,AE_FMT_S16NE,AE_FMT_S16LE
23:48:38 T:3041165872  ** ERROR: ActiveAE::Resume - failed to init**
23:48:38 T:3041165872  ** FATAL: ProcessMessage: Failed to restart AudioEngine after return from external player**
```
**Other errors seen in previous crash:**
```
23:38:54 T:3031430208  NOTICE: CAESinkOSS::EnumerateDevicesEx - No OSS mixer device present: /dev/mixer
23:38:54 T:3031430208  NOTICE: No Devices found - retry: 4
23:38:55 T:3031430208  NOTICE: CAESinkOSS::EnumerateDevicesEx - No OSS mixer device present: /dev/mixer
23:38:55 T:3031430208  NOTICE: No Devices found - retry: 3
23:38:57 T:3031430208  NOTICE: CAESinkOSS::EnumerateDevicesEx - No OSS mixer device present: /dev/mixer
23:38:57 T:3031430208  NOTICE: No Devices found - retry: 2
23:38:59 T:3031430208  NOTICE: CAESinkOSS::EnumerateDevicesEx - No OSS mixer device present: /dev/mixer
23:38:59 T:3031430208  NOTICE: No Devices found - retry: 1
23:38:59 T:3041489456   ERROR: ActiveAE::Resume - **failed to init**
23:38:59 T:3041489456   FATAL: ProcessMessage: Failed to restart AudioEngine after return from external player
23:38:59 T:3041489456   ERROR: ActiveAE::Resume -** failed to init**
23:38:59 T:3041489456   FATAL: ProcessMessage: Failed to restart AudioEngine after return from external player
```
```
23:44:04 T:2898609216  NOTICE: -->Python Interpreter Initialized<--
23:44:05 T:2726294592  NOTICE: version 3.1.5 started
23:44:05 T:2726294592  NOTICE: finished
23:44:06 T:2768237632  NOTICE: Universal - An Addons Toolkit: -watchhistory- -Loading sqlite3 as DB engine version: 3.11.0
23:44:06 T:2768237632  NOTICE: Universal - An Addons Toolkit: - watchhistory - -Auto Cleanup Start
23:44:06 T:2768237632  NOTICE: Universal - An Addons Toolkit: -watchhistory- -DELETE FROM watch_history WHERE lastwatched < '2016-02-28'
23:44:06 T:2768237632  NOTICE: Universal - An Addons Toolkit: - watchhistory - -Auto Cleanup End
23:44:10 T:2549208128 WARNING: HTTP Error 429: Bandwidth Error
23:44:27 T:2582729792   **ERROR: GetDirectory - Error getting**
23:44:34 T:2806334528  NOTICE: Thread BackgroundLoader start, auto delete: false
23:44:34 T:2806334528  NOTICE: Thread JobWorker start, auto delete: true
23:44:48 T:2726294592  NOTICE: Previous line repeats 2 times.
23:44:48 T:2726294592  NOTICE: Thread LanguageInvoker start, auto delete: false
```
**Error seen in console buffer when Kodi restarted from terminal**
[press control-C after freeze]
```
sh: nmblookup: not found
sh: nmblookup: not found
sh: nmblookup: not found
sh: nmblookup: not found
sh: nmblookup: not found
sh: nmblookup: not found
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

Exception in thread Thread-1:
Traceback (most recent call last):

  File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/OpenELEC-settings-0.6.12/.install_pkg/usr/share/kodi/addons/service.openelec.settings/resources/lib/modules/system.py", line 865, in run
  File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 403, in wait
  File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 262, in wait

KeyboardInterrupt
```

**Comment by UC3829** [comment]
**Other errors reported by dmesg**
```
[    1.111374@0] hdmitx: edid: edid ready
[    1.114211@0] hdmitx: edid: 171 errors between two reading
[    1.119680@0] hdmitx: edid: check sum valid
[    1.123854@0] hdmitx: edid: check sum valid
[    1.128009@0] hdmitx: edid: blk0 raw data

[    4.431042@0] -------hcd->flags.d32 = 0
[    4.431072@0] Init: Port Power? op_state=1
[    4.431074@0] Init1: Power Port (0)
[    4.431078@0] set usb port power on (board gpio 104)!
[    4.449232@1] aml_chip->oob_fill_cnt =168,aml_chip->oob_size =744,bch_bytes = 70
[    4.456518@1] multi plane error for selected plane mode: NAND_TWO_PLANE_MODE force plane to : NAND_SINGLE_PLANE_MODE
[    4.467022@1]  oob layout use nand base oob layout oobsize = 16,oobmul =1,mtd ->oobsize =744,aml_chip->oob_size =744
```
```
[    6.461701@1] Meson KeyInput init
[    6.464970@1] Key 116 registed.
[    6.468170@1] input: key_input as /devices/platform/key_input.4/input/input5
[    6.475303@1] Meson KeyInput register RTC interrupt
[    6.479718@1] Meson KeyInput major=239
[    6.485622@1] mmc driver version: 1.07, 2015-01-21: fix a bug in tuning which caused eMMC data CRC error
```
```
[    7.731736@1] i2c i2c-1: [aml_i2c_xfer] error ret = -5 (-EIO) token 1, master_no(1) 300K addr 0x6c
[    7.740638@1] i2c i2c-1: [aml_i2c_xfer] error ret = -5 (-EIO) token 1, master_no(1) 300K addr 0x6c
[    7.749595@1] i2c i2c-1: [aml_i2c_xfer] error ret = -5 (-EIO) token 1, master_no(1) 300K addr 0x6c
[    7.758487@1] i2c i2c-1: i2c wr failed=-11 reg=00
[    7.763300@1] i2c i2c-1: [aml_i2c_xfer] error ret = -5 (-EIO) token 1, master_no(1) 300K addr 0x6e
[    7.772239@1] i2c i2c-1: [aml_i2c_xfer] error ret = -5 (-EIO) token 1, master_no(1) 300K addr 0x6e
[    7.781179@1] i2c i2c-1: [aml_i2c_xfer] error ret = -5 (-EIO) token 1, master_no(1) 300K addr 0x6e
[    7.790073@1] i2c i2c-1: i2c wr failed=-11 reg=00
```
```
[    8.550906@1] ALSA device list:
[    8.555828@1]   #0: AML-DUMMY-CODEC
[    8.563461@1] Freeing unused kernel memory: 3108K (c0776000 - c0a7f000)
[    8.601511@0] tvmode set to 1080p
[    8.601511@0]
[    8.601541@0] don't set the same mode as current.
[    8.602232@0] osd0 free scale DISABLE
[    8.663039@0] vfm_map_store:rm default
[    8.663039@0]
[    8.663134@0] vfm_map_store:add default decoder ppmgr deinterlace amvideo
[    8.663134@0]
[    8.888974@0] mmcblk0: r/w command failed, status = 0x80000b00

[    8.888999@0] end_request: I/O error, dev mmcblk0, sector 15564680
[    8.889015@0] Buffer I/O error on device mmcblk0p2, logical block 1814001
[    8.889040@0] end_request: I/O error, dev mmcblk0, sector 15564688
[    8.889049@0] Buffer I/O error on device mmcblk0p2, logical block 1814002
[    8.889058@0] end_request: I/O error, dev mmcblk0, sector 15564696
[    8.889065@0] Buffer I/O error on device mmcblk0p2, logical block 1814003
[    8.889074@0] end_request: I/O error, dev mmcblk0, sector 15564704
[    8.889090@0] Buffer I/O error on device mmcblk0p2, logical block 1814004
[    8.889097@0] end_request: I/O error, dev mmcblk0, sector 15564712
[    8.889103@0] Buffer I/O error on device mmcblk0p2, logical block 1814005
[    8.889110@0] end_request: I/O error, dev mmcblk0, sector 15564720
[    8.889116@0] Buffer I/O error on device mmcblk0p2, logical block 1814006
[    8.889121@0] end_request: I/O error, dev mmcblk0, sector 15564728
[    8.889127@0] Buffer I/O error on device mmcblk0p2, logical block 1814007
[    8.889132@0] end_request: I/O error, dev mmcblk0, sector 15564736
[    8.889137@0] Buffer I/O error on device mmcblk0p2, logical block 1814008
[    8.889143@0] end_request: I/O error, dev mmcblk0, sector 15564744
[    8.889149@0] Buffer I/O error on device mmcblk0p2, logical block 1814009
[    8.889155@0] end_request: I/O error, dev mmcblk0, sector 15564752
[    8.889161@0] Buffer I/O error on device mmcblk0p2, logical block 1814010

[   13.001338@0] force enable DISCARD here for ext4 fs
[   13.001361@0] EXT4-fs (mmcblk0p2): couldn't mount as ext3 due to feature incompatibilities
[   13.002305@0] force enable DISCARD here for ext4 fs
[   13.002316@0] EXT4-fs (mmcblk0p2): couldn't mount as ext2 due to feature incompatibilities
[   13.003151@0] force enable DISCARD here for ext4 fs
[   13.034840@0] checked enable EXT4 DISCARD here
[   13.034857@0] EXT4-fs (mmcblk0p2): mounting with "discard" option, but the device does not support discard
[   13.034865@0] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[   13.350030@0] systemd[1]: systemd 219 running in system mode. (-PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL-XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN)
```
```
[   15.771078@0] [aml_sdio_timeout] time_start_cnt:999
[   15.771078@0] [aml_sdio_print_err] sdio: Timeout error, Cmd52 arg 0xc00, Xfer 0 Bytes, host->xfer_step=14, host->cmd_is_stop=0, pdata->port=0, virqs=0x113, virqc=0x1f001f00, conf->cmd_clk_divide=249, pdata->clkc=249, conf->bus_width=0, pdata->width=0, conf=0x416270f9, clock=400000
[   15.771078@0] [aml_sdio_timeout] time_start_cnt:999
[   15.771078@0] [aml_sdio_print_err] sdio: Timeout error, Cmd52 arg 0x80000c08, Xfer 0 Bytes, host->xfer_step=14, host->cmd_is_stop=0, pdata->port=0, virqs=0x13, virqc=0x1f003f00, conf->cmd_clk_divide=249, pdata->clkc=249, conf->bus_width=0, pdata->width=0, conf=0x416270f9, clock=400000
[   15.771078@0]
[   17.771079@0] [aml_sdio_timeout] time_start_cnt:995
[   17.771079@0] <4>[   17.780352@0] sdio: queuing unknown CIS tuple 0x80 (2 bytes)

[   17.771141@0] [aml_sdio_print_err] sdio: Timeout error, Cmd8 arg 0x1aa, Xfer 0 Bytes, host->xfer_step=14, host->cmd_is_stop=0, pdata->port=0, virqs=0x13, virqc=0x3f003f00, conf->cmd_clk_divide=249, pdata->clkc=249, conf->bus_width=0, pdata->width=0, conf=0x416270f9, clock=400000
[   17.771141@0]

[   17.783076@0] sdio: queuing unknown CIS tuple 0x80 (3 bytes)
[   17.784592@0] sdio: queuing unknown CIS tuple 0x80 (3 bytes)
[   17.787307@0] sdio: queuing unknown CIS tuple 0x80 (7 bytes)
[   17.805747@0] sdio: new high speed SDIO card at address 0001, clock 50000000, 4-bit-bus-width
[   17.812724@0] [sdio_reinit] finish
```
```
[   18.920992@0] Console: switching to colour dummy device 80x30
[   19.586066@1] mmcblk0: r/w command failed, status = 0x80000b00
[   19.586109@1] blk_update_request: 3 callbacks suppressed
[   19.586115@1] end_request: I/O error, dev mmcblk0, sector 15564680
[   19.586145@1] quiet_error: 3 callbacks suppressed

[   19.586156@1] Buffer I/O error on device mmcblk0p2, logical block 7256004
[   19.586207@1] end_request: I/O error, dev mmcblk0, sector 15564682
[   19.586233@1] Buffer I/O error on device mmcblk0p2, logical block 7256005
[   19.586244@1] end_request: I/O error, dev mmcblk0, sector 15564684
[   19.586251@1] Buffer I/O error on device mmcblk0p2, logical block 7256006
[   19.586259@1] end_request: I/O error, dev mmcblk0, sector 15564686
[   19.586266@1] Buffer I/O error on device mmcblk0p2, logical block 7256007
[   19.586295@1] end_request: I/O error, dev mmcblk0, sector 15564688
[   19.586304@1] Buffer I/O error on device mmcblk0p2, logical block 7256008
[   19.586314@1] end_request: I/O error, dev mmcblk0, sector 15564690
[   19.586320@1] Buffer I/O error on device mmcblk0p2, logical block 7256009
[   19.586328@1] end_request: I/O error, dev mmcblk0, sector 15564692
[   19.586335@1] Buffer I/O error on device mmcblk0p2, logical block 7256010
[   19.586343@1] end_request: I/O error, dev mmcblk0, sector 15564694
[   19.586351@1] Buffer I/O error on device mmcblk0p2, logical block 7256011
[   19.586360@1] end_request: I/O error, dev mmcblk0, sector 15564696
[   19.586368@1] Buffer I/O error on device mmcblk0p2, logical block 7256012
[   19.586376@1] end_request: I/O error, dev mmcblk0, sector 15564698
[   19.586383@1] Buffer I/O error on device mmcblk0p2, logical block 7256013

[   19.807452@1] The PHY does not support set_wol, was CONFIG_MICREL_PHY enabled ?
[   20.151497@1] netdev_open
[   20.151516@1] Ethernet reset
[   20.151525@1] NET MDA descpter start addr=ec83c000
[   20.151978@1] phy_interface = 1
[   20.151986@1] aml_phy_init:  trying to attach to 0:01
```
