### ISSUE TITLE
Unable to open OpenElec OS Settings menu

### ISSUE THREAD

**Issue by hollisterca** [OpenELEC/OpenELEC.tv#5044]
Kodi 17.1 Openelec 8.0.3 raspberry 2
Message is when clicking Settings - OpenELEC:
Settings addon is not yet read, please try again later.

Not sure what I can do at this point.

**Comment by sraue** [comment]
can you enable debuging in kodi, and paste kodi.log after you get this message?

**Comment by hollisterca** [comment]
Will this do?
[01_Kodi_Settings.log.zip](https://github.com/OpenELEC/OpenELEC.tv/files/992944/01_Kodi_Settings.log.zip)

**Comment by sraue** [comment]
its the right file but not much output, can you paste a longer file which shows all messages from boot until kodi is started

**Comment by hollisterca** [comment]
Hello,
I booted on May 13 the rasp. and then enabled Debug logging, then clicked on Settings - OpenELEC, disabled logging. Then accessed the share Logfiles via smb. and I get the following files.
see attached
![logfiles](https://cloud.githubusercontent.com/assets/23412806/26023000/210c4a8c-37b3-11e7-8d4b-9ad7edcf7e54.jpg)
I did check 01_KODI.log and searched for "May 13" and nothing. So it is not recording the problem.
I checked some of the other files but do not see any issues.

**Comment by hollisterca** [comment]
Upgraded to 8.0.4
still the same issue

Found this in the log

11:11:49.548 T:1722946464   ERROR: ## OpenELEC Addon ## oe::load_config ## ERROR: (ExpatError('not well-formed (invalid token): line 1, column 1',))
11:11:49.550 T:1722946464   ERROR: Traceback (most recent call last):
                                              File "/home/stephan/projects/openelec-8.0.git/build.OpenELEC-RPi2.arm-8.0.4/OpenELEC-settings-0.8.1/.install_pkg/usr/share/kodi/addons/service.openelec.settings/oe.py", line 536, in load_config
                                              File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
                                              File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
                                              File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
                                            ExpatError: not well-formed (invalid token): line 1, column 1
11:11:49.550 T:1722946464   ERROR: ## OpenELEC Addon ## oe::read_setting ## ERROR: (AttributeError("'NoneType' object has no attribute 'getElementsByTagName'",))
11:11:49.551 T:1722946464   ERROR: Traceback (most recent call last):
                                              File "/home/stephan/projects/openelec-8.0.git/build.OpenELEC-RPi2.arm-8.0.4/OpenELEC-settings-0.8.1/.install_pkg/usr/share/kodi/addons/service.openelec.settings/oe.py", line 603, in read_setting
                                            AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'
